/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.aiod.common

class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

