/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
   
    application
}


dependencies {
	implementation(project(":common"))
	}

application {
    // Define the main class for the application
    mainClassName = "com.aiod.core.AppKt"
}
